spring.application.name=UniformOrderSystem2
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/uniformdb
spring.datasource.username=root
spring.datasource.password=root123
spring.mail.host=sv5215.xserver.jp
spring.mail.port=587
spring.mail.username=system.project.team05@kanda-it-school-system.com
spring.mail.password=8FDP8wCEo5Gej8W
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.servlet.session.timeout=10m
